### ISSUE TITLE
Test case 만들기

### ISSUE THREAD

**Issue by kiyoung-Lee** [jiso16/Terminal#1]
터미널 프로그램에서 발생할수 있는 모든 경우의 수를 나열해 보세요.

ex)
1. ls 를 입력하면 디렉토리 내 파일 & 폴더를 출력한다. 
2. ls 를 입력하면 비어있는 디렉토리의 경우 아무런 동작도 하지 않는다.

**Comment by jiso16** [comment]
1. Ls를 입력했을 때
- 폴더/파일명 출력
- 입력하면 비어있는 디렉토리의 경우 아무런 동작도 하지 않는다
	
2. Cd 입력했을 때
- 경로이동
- 폴더명/ 파일명 출력 안 함
- cd 파일명 입력하면 오류출력
- 빈폴더에서 cd입력하면 아무일도 안 일어남

3. Cd .. 입력했을 때
- 상위폴더로 이동
- 폴더명/ 파일명 출력 안 함
- 상위폴더가 없을경우 아무일도 안 일어남

**Comment by kiyoung-Lee** [comment]
cd 입력했을때 -> cd [디렉토리명] 입력햇을때가 맞을거 같아요.
빈폴더에서 cd입력하면 아무일도 안 일어남 -->  빈폴더에 cd 를 하면 빈 폴더로 들어가져야 하지 않을까요~?

cd [없는 디렉토리] 일때
cd [올바른 디렉토리] 일때

는 어떻게 될까요? 

ls 로 파일명을 검색한다(a,b,c 폴더가 있다) -> cd a 입력 -> ls 하면 어떤게 나와야 하나요?
ls 로 파일명을 검색한다(a,b,c 폴더가 있다) -> cd test 입력 하면 어떤게 나와야 하나요?
ls 로 파일명을 검색한다(a,b,c 폴더가 있다) -> cd a 입력 -> cd .. 입력 -> ls 하면 어떤게 나와야 하나요?
ls 로 파일명을 검색한다(a,b,c 폴더가 있다) -> cd a 입력 -> ls(d,e,f 폴더가 있다.) -> cd e 입력 -> ls 입력 하면 어떤게 나와야 하나요?
ls 로 파일명을 검색한다(a,b,c 폴더가 있다) -> cd a 입력 -> ls(d,e,f 폴더가 있다.) -> cd test 입력 하면 어떤게 나와야 하나요

**Comment by jiso16** [comment]
1. ls를 입력했을 때
- 폴더/파일명 출력
- 비어있는 디렉토리의 경우 아무런 동작도 하지 않는다
	
2. cd [디렉토리명] 입력했을 때
- cd [없는 디렉토리]일 때 - 아무런 처리도 하지 않음
- cd [올바른 디렉토리]일 때 - 입력한 디렉토리로 이동

3. cd .. 입력했을 때
- 상위폴더로 이동
- 폴더명/ 파일명 출력 안 함
- 상위폴더가 없을경우 아무일도 안 일어남

1) (a,b,c 폴더가 있다) cd a 입력 = ls 입력하면 a 디렉토리의 파일/폴더명 출력, 아무것도 없을경우 아무것도 출력 안함
2) (a,b,c 폴더가 있다) cd test 입력 = 아무 처리도 하지 않음
3) (a,b,c 폴더가 있다) cd a 입력 -> cd .. 입력 = ls입력 하면 a,b,c, 폴더 출력
4) (a,b,c 폴더가 있다) cd a 입력 -> ls(d,e,f 폴더가 있다.)-> cd e 입력 -> ls 입력 =  e 디렉토리의 파일/폴더명을 출력 , 아무것도 없을경우 아무것도 출력 안함
5) (a,b,c 폴더가 있다) cd a 입력 -> ls(d,e,f 폴더가 있다.)-> cd test입력 -> 아무런 처리도 하지 않음
