### ISSUE TITLE
rm 삭제명령어 TestCase

### ISSUE THREAD

**Issue by kiyoung-Lee** [jiso16/Terminal#4]

**Comment by jiso16** [comment]
- rmdir [제거할 디렉토리명]
1. 현재 경로에 입력한 [디렉토리명] 없을 때: 디렉토리가 지워지지 않음
2. 현재 경로에 입력한 [디렉토리명]이 있을 때: 입력한 디렉토리가 지워짐
3. 입력한 디렉토리 안에 파일이 존재할 때: 파일이 있을 경우 동작을 안함, 디렉토리가 지워지지 않음
